### ISSUE TITLE
Nice, but breaks functional style

### ISSUE THREAD

**Issue by chakravala** [jlapeyre/DotCall.jl#1]
While it's neat that you can formalize things like this in Julia, ultimately you are breaking the functional style.

In the end, you are still writing the same thing, just in a different order and a less functional style.

While I may not be able to think of disadvantages, I also cannot think of any advantages to this either.

**Comment by jlapeyre** [comment]
Thanks for the comment. This package presupposes that the concept is worth exploring. It's definitely worthwhile criticizing the whole idea, and the need for a package. But this package's development space is not the forum for it.
